export const FOOTER__DATA = [
    {
        id: 1,
        title: 'Legal',
        path1: 'About Us',
        path2: 'Carrier',
        path3: 'We Are Hiring',
        path4: 'Blog',
        hide: false,
    },
    {
        id: 2,
        title: 'Company Info',
        path1: 'About Us',
        path2: 'Carrier',
        path3: 'We Are Hiring',
        path4: 'Blog',
        hide: false,
    },
    {
        id: 3,
        title: 'Features',
        path1: 'Business Marketing',
        path2: 'User Analytic',
        path3: 'Live Chat',
        path4: 'Unlimited Support',
        hide: false,
    },
    {
        id: 4,
        title: 'Resources',
        path1: 'Watch a Demo',
        path2: 'Customers',
        path3: 'API',
        hide: false,
    },
    {
        id: 5,
        title: 'Get In Touch',
        path1: '(480) 555-0103',
        path2: '517 Washington Ave.',
        path3: 'debra.holt@example.com',
        hide: false,
    },
]